"""auto-vote

Revision ID: 946c239f1cc1
Revises: 4a66c03ac6de
Create Date: 2022-02-04 18:31:16.179488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946c239f1cc1'
down_revision = '4a66c03ac6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
